/*
 * Authentication System
 * Handles login and secure connection to the software
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AccessTokenCheckResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-05-10T17:25:02.593Z")
public class AccessTokenCheckResponse {
  @SerializedName("canAccess")
  private Boolean canAccess = null;

  public AccessTokenCheckResponse canAccess(Boolean canAccess) {
    this.canAccess = canAccess;
    return this;
  }

   /**
   * Can the token provided access the desired function
   * @return canAccess
  **/
  @ApiModelProperty(value = "Can the token provided access the desired function")
  public Boolean isCanAccess() {
    return canAccess;
  }

  public void setCanAccess(Boolean canAccess) {
    this.canAccess = canAccess;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessTokenCheckResponse accessTokenCheckResponse = (AccessTokenCheckResponse) o;
    return Objects.equals(this.canAccess, accessTokenCheckResponse.canAccess);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canAccess);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessTokenCheckResponse {\n");
    
    sb.append("    canAccess: ").append(toIndentedString(canAccess)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

