/*
 * Product Management
 * Handles products, location and barcodes
 *
 * OpenAPI spec version: 0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Location
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-05-26T10:45:52.245Z")
public class Location {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("AmountOfUniqueProducts")
  private Integer amountOfUniqueProducts = null;

  public Location name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Location name
   * @return name
  **/
  @ApiModelProperty(value = "Location name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Location amountOfUniqueProducts(Integer amountOfUniqueProducts) {
    this.amountOfUniqueProducts = amountOfUniqueProducts;
    return this;
  }

   /**
   * Amount of different products on location
   * @return amountOfUniqueProducts
  **/
  @ApiModelProperty(value = "Amount of different products on location")
  public Integer getAmountOfUniqueProducts() {
    return amountOfUniqueProducts;
  }

  public void setAmountOfUniqueProducts(Integer amountOfUniqueProducts) {
    this.amountOfUniqueProducts = amountOfUniqueProducts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Location location = (Location) o;
    return Objects.equals(this.name, location.name) &&
        Objects.equals(this.amountOfUniqueProducts, location.amountOfUniqueProducts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, amountOfUniqueProducts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Location {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    amountOfUniqueProducts: ").append(toIndentedString(amountOfUniqueProducts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

